[project]
name = "cvdpack"
version = "0.5.2"
license = {text = "BSD-3-Clause"}
license-files = ["LICENSE"]
description = "Quantize and video-compress your RGB/Depth/Flow/SurfaceNormal datasets"
readme = "README.md"
authors = [
    { name = "Alexander Raistrick", email = "araistrick@princeton.edu" }
]

keywords = [
    "computer vision",
    "datasets"
]
classifiers = [
    "Programming Language :: Python :: 3",
]

requires-python = ">3.10.0"
dependencies = [
    "numpy>=1.23.5,<2",
    "opencv-python>=4.7.0.68",
    "tqdm>=4.60.0"
]

[project.scripts]
cvdpack = "cvdpack.main:main"

[project.optional-dependencies]
slurm = [
    "submitit",
    "setuptools", # submitit implicitly depends on pkg_resources which is no longer available in newer python versions
]
dev = [
    "ruff",
    "matplotlib>=3.6.2",
    "pytest>=7.2,<10"
]
test = [
    "pytest>=7.2,<10"
]

[build-system]
# based on https://github.com/astral-sh/trusted-publishing-examples/blob/main/pyproject.toml
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff.lint]
select = [
    "E",
    "I",
    "F",
    "S102", # no exec()
    "TID252", # relative imports only allowed for siblings
]
ignore = [
    "E501", # over-length lines, formatter should handle it
    "E741", # ambiguous variable name
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
