[project]
name = "cvdpack"
version = "0.0.2"
license = {text = "BSD-3-Clause"}
license-files = ["LICENSE"]
description = "Quantize and video-compress your RGB/Depth/Flow/SurfaceNormal datasets"
readme = "README.md"
authors = [
    { name = "Alexander Raistrick", email = "araistrick@princeton.edu" }
]

keywords = [
    "computer vision",
    "datasets"
]
classifiers = [
    "Programming Language :: Python :: 3",
]

requires-python = ">3.11.0"
dependencies = [
    "numpy<2",
    "opencv-python",
    "tqdm"
]
dev = [
    "ruff",
]

[project.scripts]
cvdpack = "cvdpack.main:main"

[project.optional-dependencies]
slurm = [
    "submitit"
]
dev = [
    "ruff",
    "matplotlib"
]

[build-system]
# based on https://github.com/astral-sh/trusted-publishing-examples/blob/main/pyproject.toml
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.3",
    "ruff>=0.7.1",
]

